# electron-builder configuration in TOML
# https://www.electron.build/configuration/configuration

# Auto Update: https://www.electron.build/auto-update

appId = "com.electron.react.typescript"
productName = "electron-react-typescript"
artifactName = "electron-react-typescript-${os}-${arch}-v${version}.${ext}"
asar = true
compression = "normal"
files = ["dist/**/*"]
extraResources = ["assets/**/*"]

[publish]
provider = "github"
releaseType = "release"
# token = "${env.GH_TOKEN}"

[directories]
buildResources = "assets/"
output = "build/"

# Windows Store App

[appx]
displayName = "electron react typescript"
identityName = "electron.react.typescript"
publisherDisplayName = "lightyen"

# Windows NSIS

[nsis]
shortcutName = "electron-react-typescript"
oneClick = false
createDesktopShortcut = false
createStartMenuShortcut = true
runAfterFinish = true

[appImage]
synopsis = "An electron sample"
description = "An electron sample which is developed with react and typescript"
category = "Development"
# license = "LICENSE"

[win]
target = ["nsis"]
# certificateFile = "certificate.pfx"
icon = "./assets/appicons/256x256.png"

[linux]
target = ["AppImage"]
executableName = "electron-react-typescript"
desktop = "electron-react-typescript"
icon = "assets/appicons/"

# For MacOS (I haven't try it yet!!!)

[mac]
target = ["default"]
category = "public.app-category.developer-tools"
