root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - emotion
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier
  - prettier/@typescript-eslint
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: "."
rules:
  spaced-comment: error
  no-var: error
  no-extra-bind: error
  prefer-arrow-callback: error
  no-empty:
    - error
    - allowEmptyCatch: true
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: none
      ignoreRestSiblings: true
      caughtErrors: none
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/camelcase": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/array-type":
    - error
    - default: array-simple
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/no-explicit-any":
    - warn
    - ignoreRestArgs: true
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
      singleline:
        delimiter: semi
        requireLast: false
  "@typescript-eslint/explicit-module-boundary-types": "off"
  react/display-name: "off"
  react/prop-types: "off"
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
settings:
  react:
    version: detect
env:
  browser: true
